### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by shishir-a412ed** [shishir-a412ed/runc-notify#1]
Let's discuss here.
Once @mrunalp gives a LGTM, I will hand this over to QE.

Shishir

**Comment by edsantiago** [comment]
Hardcoded `docker` won't work when `docker-latest` is the active service. Easy to fix on our end.

Don't forget to `daemon-reload` after rm'ing the unit file.

`runc` is in `/usr/bin` on my (RHEL7) system, not `/usr/local/sbin`. Is that a debug setup on your end? My suggestion would be to change the unit file to /usr/bin/runc, or (if absolutely necessary) to use a sed filter when installing it. 

Looks good. Thank you.

**Comment by mrunalp** [comment]
set -e in the bash script.

**Comment by mrunalp** [comment]
Otherwise looks fine :+1:

**Comment by shishir-a412ed** [comment]
@mrunalp When I build runc from source code, {`make; sudo make install`}. The binary gets installed at `/usr/local/sbin/runc`. Do we need to use `/usr/local/sbin/runc` or /usr/bin/runc` (as ed suggested) ?

**Comment by cevich** [comment]
Some reason you can't just call `runc` and let `$PATH` figure it out?

**Comment by edsantiago** [comment]
@cevich systemd unit files require absolute path in `ExecStart` and `ExecStop`; see `systemd.service`

**Comment by edsantiago** [comment]
@shishir-a412ed this isn't actually working as expected. A few gripes:

   755 should be 644 (systemd unit files should not be executable)
   runc run should be runc start (there's no run command)

With those fixed, it still doesn't work: systemd start times out. My hunch is that something is needed in config.json to bind-mount the systemd socket and pass the NOTIFY_SOCKET envariable. But I haven't been able to figure that out. I'll keep working on it, but if this is an easy one for you to investigate, please let me know.

**Comment by edsantiago** [comment]
See pull request #2

**Comment by shishir-a412ed** [comment]
@edsantiago 

1) okay I was using `runc` upstream (I build it from the source: version 1.0.0-rc2) and that has a `runc run` command. I will discuss this with @mrunalp. I think eventually we would need `runc run` which creates and run a new container and not `runc start`  which executes a user defined process in a  already created container.

2)  We don't need to bind mount the systemd socket or pass the `NOTIFY_SOCKET` environment variable. No need to put these changes in `config.json`. runc takes care of all these things. We have implemented that in the runc code. That's the feature we are trying to test :)

Shishir

**Comment by edsantiago** [comment]
@shishir-a412ed ah, ok, so my first step has to be to find a build of runc that includes both the `run` command and the sdnotify scaffolding. Thank you!

**Comment by mrunalp** [comment]
@shishir-a412ed We should be okay using runc run for this test.

**Comment by mrunalp** [comment]
@edsantiago Yes, using runc from master (>1.0.0.rc1) should work.
